### trapti patel
this is core python learning

---

In [6]:
for i in range(7):
    print(i,end="-")

0-1-2-3-4-5-6-

In [9]:
import numpy as np
import pandas as pd

In [10]:
dict={"name":["tp","sp","sp","np","mp"],
      "age":[20,19,10,40,30],
      "wt":[40,40,20,60,50]
    }

In [11]:
df=pd.DataFrame(dict)

In [12]:
df

  name  age  wt
0   tp   20  40
1   sp   19  40
2   sp   10  20
3   np   40  60
4   mp   30  50

In [13]:
df.to_csv('family_rm_index.csv',index=False)

In [14]:
df.head(2)

  name  age  wt
0   tp   20  40
1   sp   19  40

In [15]:
df.tail(2)

  name  age  wt
3   np   40  60
4   mp   30  50

In [16]:
df.describe()

             age         wt
count   5.000000   5.000000
mean   23.800000  42.000000
std    11.497826  14.832397
min    10.000000  20.000000
25%    19.000000  40.000000
50%    20.000000  40.000000
75%    30.000000  50.000000
max    40.000000  60.000000

In [17]:
family=pd.read_csv('family.csv')

In [18]:
family

   Unnamed: 0 name  age  wt
0           0   tp   20  40
1           1   sp   19  40
2           2   sp   10  20
3           3   np   40  60
4           4   mp   30  50

In [19]:
family["age"]

0    20
1    19
2    10
3    40
4    30
Name: age, dtype: int64

In [21]:
type(family["age"])

pandas.core.series.Series

In [22]:
type(family)

pandas.core.frame.DataFrame

In [23]:
family["age"][0]

np.int64(20)

In [24]:
family["age"][0]=21

C:\Users\user\AppData\Local\Temp\ipykernel_11760\70725820.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  family["age"][0]=21

In [25]:
family.to_csv('family.csv',index=False)

In [26]:
family

   Unnamed: 0 name  age  wt
0           0   tp   21  40
1           1   sp   19  40
2           2   sp   10  20
3           3   np   40  60
4           4   mp   30  50

In [27]:
family.index=['I','II','III','IV','V']

In [28]:
family.to_csv('family.csv')

In [29]:
family

     Unnamed: 0 name  age  wt
I             0   tp   21  40
II            1   sp   19  40
III           2   sp   10  20
IV            3   np   40  60
V             4   mp   30  50

In [31]:
ser=pd.Series(np.random.rand(34))

In [32]:
ser

0     0.232788
1     0.169530
2     0.171444
3     0.172679
4     0.013481
5     0.806965
6     0.255993
7     0.599964
8     0.090719
9     0.478141
10    0.674867
11    0.173282
12    0.375133
13    0.768185
14    0.666237
15    0.799145
16    0.592517
17    0.316535
18    0.858699
19    0.473693
20    0.374012
21    0.763777
22    0.405520
23    0.622547
24    0.926300
25    0.980273
26    0.089606
27    0.516521
28    0.321163
29    0.370875
30    0.630870
31    0.264668
32    0.251670
33    0.038214
dtype: float64