In [1]:
import pandas as pd

In [2]:
family=pd.read_csv('family.csv')

In [3]:
family

  Unnamed: 0.1  Unnamed: 0 name  age  wt
0            I           0   tp   21  40
1           II           1   sp   19  40
2          III           2   sp   10  20
3           IV           3   np   40  60
4            V           4   mp   30  50

In [4]:
import numpy as np
import matplotlib.pyplot as plt

In [5]:
df=family

In [6]:
df.head

<bound method NDFrame.head of   Unnamed: 0.1  Unnamed: 0 name  age  wt
0            I           0   tp   21  40
1           II           1   sp   19  40
2          III           2   sp   10  20
3           IV           3   np   40  60
4            V           4   mp   30  50>

In [9]:
df

  Unnamed: 0.1  Unnamed: 0 name  age  wt
0            I           0   tp   21  40
1           II           1   sp   19  40
2          III           2   sp   10  20
3           IV           3   np   40  60
4            V           4   mp   30  50

In [10]:
x=family
y=df.target

AttributeError: 'DataFrame' object has no attribute 'target'