In [1]:
import numpy as np
import pandas as pd

In [2]:
newdf=pd.DataFrame(np.random.rand(334,5),index=np.arange(334))

In [3]:
newdf.head()

          0         1         2         3         4
0  0.218370  0.682398  0.660739  0.964293  0.332738
1  0.987456  0.760719  0.042941  0.439698  0.930810
2  0.339867  0.926514  0.560698  0.833263  0.685824
3  0.508694  0.491297  0.931238  0.862389  0.306098
4  0.333914  0.049874  0.788520  0.298697  0.044108

In [4]:
newdf

            0         1         2         3         4
0    0.218370  0.682398  0.660739  0.964293  0.332738
1    0.987456  0.760719  0.042941  0.439698  0.930810
2    0.339867  0.926514  0.560698  0.833263  0.685824
3    0.508694  0.491297  0.931238  0.862389  0.306098
4    0.333914  0.049874  0.788520  0.298697  0.044108
..        ...       ...       ...       ...       ...
329  0.835277  0.514215  0.330844  0.572943  0.014980
330  0.743643  0.046142  0.096495  0.235695  0.793449
331  0.792602  0.639721  0.432425  0.023883  0.797337
332  0.656214  0.487085  0.558181  0.731227  0.674087
333  0.863502  0.669050  0.329836  0.295134  0.081340

[334 rows x 5 columns]

In [5]:
type(newdf)

pandas.core.frame.DataFrame

In [6]:
type(newdf[1])

pandas.core.series.Series

In [7]:
newdf.dtypes

0    float64
1    float64
2    float64
3    float64
4    float64
dtype: object

In [8]:
newdf[0].dtypes

dtype('float64')

In [9]:
newdf[0][0]="trepti"

C:\Users\user\AppData\Local\Temp\ipykernel_6436\224884604.py:1: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  newdf[0][0]="trepti"
C:\Users\user\AppData\Local\Temp\ipykernel_6436\224884604.py:1: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value 'trepti' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  newdf[0][0]="trepti"

In [10]:
newdf[0].dtypes

dtype('O')

In [11]:
newdf.dtypes

0     object
1    float64
2    float64
3    float64
4    float64
dtype: object

In [12]:
newdf.head

<bound method NDFrame.head of             0         1         2         3         4
0      trepti  0.682398  0.660739  0.964293  0.332738
1    0.987456  0.760719  0.042941  0.439698  0.930810
2    0.339867  0.926514  0.560698  0.833263  0.685824
3    0.508694  0.491297  0.931238  0.862389  0.306098
4    0.333914  0.049874  0.788520  0.298697  0.044108
..        ...       ...       ...       ...       ...
329  0.835277  0.514215  0.330844  0.572943  0.014980
330  0.743643  0.046142  0.096495  0.235695  0.793449
331  0.792602  0.639721  0.432425  0.023883  0.797337
332  0.656214  0.487085  0.558181  0.731227  0.674087
333  0.863502  0.669050  0.329836  0.295134  0.081340

[334 rows x 5 columns]>

In [13]:
newdf.index

Index([  0,   1,   2,   3,   4,   5,   6,   7,   8,   9,
       ...
       324, 325, 326, 327, 328, 329, 330, 331, 332, 333],
      dtype='int64', length=334)

In [14]:
newdf.columns

RangeIndex(start=0, stop=5, step=1)

In [15]:
newdf.to_numpy()

array([['trepti', 0.682397928113232, 0.6607390727926113,
        0.9642928823969759, 0.33273776058669247],
       [0.987455844783493, 0.7607186495549305, 0.04294143773949555,
        0.4396982507557542, 0.9308104898699362],
       [0.3398670019221802, 0.9265139395644716, 0.5606976774511943,
        0.8332630040477572, 0.6858241687603389],
       ...,
       [0.7926016945524911, 0.6397213423605477, 0.4324254458624467,
        0.023882973236485916, 0.7973365292595104],
       [0.6562140286550494, 0.48708524458486624, 0.558181482381854,
        0.7312272773460754, 0.6740870236300105],
       [0.8635018054008189, 0.6690496166452653, 0.32983578957668,
        0.29513434024752716, 0.081339534061458]], dtype=object)

In [16]:
newdf[0][0]=0.2344

In [17]:
newdf.dtypes

0     object
1    float64
2    float64
3    float64
4    float64
dtype: object

In [18]:
newdf.T

,0,1,2,3,4,5,6,7,8,9,...,324,325,326,327,328,329,330,331,332,333
0,0.2344,0.987456,0.339867,0.508694,0.333914,0.471778,0.875859,0.934051,0.81707,0.72908,...,0.11464,0.002955,0.917322,0.285912,0.925641,0.835277,0.743643,0.792602,0.656214,0.863502
1,0.682398,0.760719,0.926514,0.491297,0.049874,0.797376,0.258019,0.78651,0.802194,0.700478,...,0.992715,0.888497,0.201336,0.713043,0.680283,0.514215,0.046142,0.639721,0.487085,0.66905
2,0.660739,0.042941,0.560698,0.931238,0.78852,0.204768,0.365322,0.40421,0.610249,0.307749,...,0.916993,0.525628,0.225456,0.89137,0.474428,0.330844,0.096495,0.432425,0.558181,0.329836
3,0.964293,0.439698,0.833263,0.862389,0.298697,0.975321,0.946751,0.778086,0.319151,0.798756,...,0.566642,0.224639,0.315894,0.320539,0.733061,0.572943,0.235695,0.023883,0.731227,0.295134
4,0.332738,0.93081,0.685824,0.306098,0.044108,0.533654,0.876808,0.744976,0.655046,0.488054,...,0.805476,0.912161,0.004916,0.328449,0.103406,0.01498,0.793449,0.797337,0.674087,0.08134

In [19]:
newdf

            0         1         2         3         4
0      0.2344  0.682398  0.660739  0.964293  0.332738
1    0.987456  0.760719  0.042941  0.439698  0.930810
2    0.339867  0.926514  0.560698  0.833263  0.685824
3    0.508694  0.491297  0.931238  0.862389  0.306098
4    0.333914  0.049874  0.788520  0.298697  0.044108
..        ...       ...       ...       ...       ...
329  0.835277  0.514215  0.330844  0.572943  0.014980
330  0.743643  0.046142  0.096495  0.235695  0.793449
331  0.792602  0.639721  0.432425  0.023883  0.797337
332  0.656214  0.487085  0.558181  0.731227  0.674087
333  0.863502  0.669050  0.329836  0.295134  0.081340

[334 rows x 5 columns]

In [20]:
newdf.head()

          0         1         2         3         4
0    0.2344  0.682398  0.660739  0.964293  0.332738
1  0.987456  0.760719  0.042941  0.439698  0.930810
2  0.339867  0.926514  0.560698  0.833263  0.685824
3  0.508694  0.491297  0.931238  0.862389  0.306098
4  0.333914  0.049874  0.788520  0.298697  0.044108

In [21]:
newdf.sort_index(axis=0,ascending=False)

            0         1         2         3         4
333  0.863502  0.669050  0.329836  0.295134  0.081340
332  0.656214  0.487085  0.558181  0.731227  0.674087
331  0.792602  0.639721  0.432425  0.023883  0.797337
330  0.743643  0.046142  0.096495  0.235695  0.793449
329  0.835277  0.514215  0.330844  0.572943  0.014980
..        ...       ...       ...       ...       ...
4    0.333914  0.049874  0.788520  0.298697  0.044108
3    0.508694  0.491297  0.931238  0.862389  0.306098
2    0.339867  0.926514  0.560698  0.833263  0.685824
1    0.987456  0.760719  0.042941  0.439698  0.930810
0      0.2344  0.682398  0.660739  0.964293  0.332738

[334 rows x 5 columns]

In [22]:
newdf2=newdf

In [23]:
newdf2

            0         1         2         3         4
0      0.2344  0.682398  0.660739  0.964293  0.332738
1    0.987456  0.760719  0.042941  0.439698  0.930810
2    0.339867  0.926514  0.560698  0.833263  0.685824
3    0.508694  0.491297  0.931238  0.862389  0.306098
4    0.333914  0.049874  0.788520  0.298697  0.044108
..        ...       ...       ...       ...       ...
329  0.835277  0.514215  0.330844  0.572943  0.014980
330  0.743643  0.046142  0.096495  0.235695  0.793449
331  0.792602  0.639721  0.432425  0.023883  0.797337
332  0.656214  0.487085  0.558181  0.731227  0.674087
333  0.863502  0.669050  0.329836  0.295134  0.081340

[334 rows x 5 columns]

In [24]:
newdf2[0][0]=0.34

In [25]:
newdf

            0         1         2         3         4
0        0.34  0.682398  0.660739  0.964293  0.332738
1    0.987456  0.760719  0.042941  0.439698  0.930810
2    0.339867  0.926514  0.560698  0.833263  0.685824
3    0.508694  0.491297  0.931238  0.862389  0.306098
4    0.333914  0.049874  0.788520  0.298697  0.044108
..        ...       ...       ...       ...       ...
329  0.835277  0.514215  0.330844  0.572943  0.014980
330  0.743643  0.046142  0.096495  0.235695  0.793449
331  0.792602  0.639721  0.432425  0.023883  0.797337
332  0.656214  0.487085  0.558181  0.731227  0.674087
333  0.863502  0.669050  0.329836  0.295134  0.081340

[334 rows x 5 columns]

In [26]:
newdf2=newdf[:]

In [27]:
newdf2[0][0]=0.45

C:\Users\user\AppData\Local\Temp\ipykernel_6436\1850289438.py:1: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  newdf2[0][0]=0.45
C:\Users\user\AppData\Local\Temp\ipykernel_6436\1850289438.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  newdf2[0][0]=0.45

In [28]:
newdf2

            0         1         2         3         4
0        0.45  0.682398  0.660739  0.964293  0.332738
1    0.987456  0.760719  0.042941  0.439698  0.930810
2    0.339867  0.926514  0.560698  0.833263  0.685824
3    0.508694  0.491297  0.931238  0.862389  0.306098
4    0.333914  0.049874  0.788520  0.298697  0.044108
..        ...       ...       ...       ...       ...
329  0.835277  0.514215  0.330844  0.572943  0.014980
330  0.743643  0.046142  0.096495  0.235695  0.793449
331  0.792602  0.639721  0.432425  0.023883  0.797337
332  0.656214  0.487085  0.558181  0.731227  0.674087
333  0.863502  0.669050  0.329836  0.295134  0.081340

[334 rows x 5 columns]

In [29]:
newdf

            0         1         2         3         4
0        0.45  0.682398  0.660739  0.964293  0.332738
1    0.987456  0.760719  0.042941  0.439698  0.930810
2    0.339867  0.926514  0.560698  0.833263  0.685824
3    0.508694  0.491297  0.931238  0.862389  0.306098
4    0.333914  0.049874  0.788520  0.298697  0.044108
..        ...       ...       ...       ...       ...
329  0.835277  0.514215  0.330844  0.572943  0.014980
330  0.743643  0.046142  0.096495  0.235695  0.793449
331  0.792602  0.639721  0.432425  0.023883  0.797337
332  0.656214  0.487085  0.558181  0.731227  0.674087
333  0.863502  0.669050  0.329836  0.295134  0.081340

[334 rows x 5 columns]

In [30]:
newdf2=newdf.copy()

In [31]:
newdf2

            0         1         2         3         4
0        0.45  0.682398  0.660739  0.964293  0.332738
1    0.987456  0.760719  0.042941  0.439698  0.930810
2    0.339867  0.926514  0.560698  0.833263  0.685824
3    0.508694  0.491297  0.931238  0.862389  0.306098
4    0.333914  0.049874  0.788520  0.298697  0.044108
..        ...       ...       ...       ...       ...
329  0.835277  0.514215  0.330844  0.572943  0.014980
330  0.743643  0.046142  0.096495  0.235695  0.793449
331  0.792602  0.639721  0.432425  0.023883  0.797337
332  0.656214  0.487085  0.558181  0.731227  0.674087
333  0.863502  0.669050  0.329836  0.295134  0.081340

[334 rows x 5 columns]

In [32]:
newdf2[0][0]=0.54

C:\Users\user\AppData\Local\Temp\ipykernel_6436\1458362357.py:1: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  newdf2[0][0]=0.54
C:\Users\user\AppData\Local\Temp\ipykernel_6436\1458362357.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  newdf2[0][0]=0.54

In [33]:
newdf

            0         1         2         3         4
0        0.45  0.682398  0.660739  0.964293  0.332738
1    0.987456  0.760719  0.042941  0.439698  0.930810
2    0.339867  0.926514  0.560698  0.833263  0.685824
3    0.508694  0.491297  0.931238  0.862389  0.306098
4    0.333914  0.049874  0.788520  0.298697  0.044108
..        ...       ...       ...       ...       ...
329  0.835277  0.514215  0.330844  0.572943  0.014980
330  0.743643  0.046142  0.096495  0.235695  0.793449
331  0.792602  0.639721  0.432425  0.023883  0.797337
332  0.656214  0.487085  0.558181  0.731227  0.674087
333  0.863502  0.669050  0.329836  0.295134  0.081340

[334 rows x 5 columns]

In [34]:
newdf2

            0         1         2         3         4
0        0.54  0.682398  0.660739  0.964293  0.332738
1    0.987456  0.760719  0.042941  0.439698  0.930810
2    0.339867  0.926514  0.560698  0.833263  0.685824
3    0.508694  0.491297  0.931238  0.862389  0.306098
4    0.333914  0.049874  0.788520  0.298697  0.044108
..        ...       ...       ...       ...       ...
329  0.835277  0.514215  0.330844  0.572943  0.014980
330  0.743643  0.046142  0.096495  0.235695  0.793449
331  0.792602  0.639721  0.432425  0.023883  0.797337
332  0.656214  0.487085  0.558181  0.731227  0.674087
333  0.863502  0.669050  0.329836  0.295134  0.081340

[334 rows x 5 columns]

In [35]:
newdf.head()

          0         1         2         3         4
0      0.45  0.682398  0.660739  0.964293  0.332738
1  0.987456  0.760719  0.042941  0.439698  0.930810
2  0.339867  0.926514  0.560698  0.833263  0.685824
3  0.508694  0.491297  0.931238  0.862389  0.306098
4  0.333914  0.049874  0.788520  0.298697  0.044108

In [36]:
newdf.loc[0,0]=0.3453

In [37]:
newdf

            0         1         2         3         4
0      0.3453  0.682398  0.660739  0.964293  0.332738
1    0.987456  0.760719  0.042941  0.439698  0.930810
2    0.339867  0.926514  0.560698  0.833263  0.685824
3    0.508694  0.491297  0.931238  0.862389  0.306098
4    0.333914  0.049874  0.788520  0.298697  0.044108
..        ...       ...       ...       ...       ...
329  0.835277  0.514215  0.330844  0.572943  0.014980
330  0.743643  0.046142  0.096495  0.235695  0.793449
331  0.792602  0.639721  0.432425  0.023883  0.797337
332  0.656214  0.487085  0.558181  0.731227  0.674087
333  0.863502  0.669050  0.329836  0.295134  0.081340

[334 rows x 5 columns]

In [38]:
newdf.columns=list("ABCDE")

In [39]:
newdf.head()

          A         B         C         D         E
0    0.3453  0.682398  0.660739  0.964293  0.332738
1  0.987456  0.760719  0.042941  0.439698  0.930810
2  0.339867  0.926514  0.560698  0.833263  0.685824
3  0.508694  0.491297  0.931238  0.862389  0.306098
4  0.333914  0.049874  0.788520  0.298697  0.044108

In [40]:
newdf.loc[0,0]=0.3456

In [41]:
newdf.head()

          A         B         C         D         E       0
0    0.3453  0.682398  0.660739  0.964293  0.332738  0.3456
1  0.987456  0.760719  0.042941  0.439698  0.930810     NaN
2  0.339867  0.926514  0.560698  0.833263  0.685824     NaN
3  0.508694  0.491297  0.931238  0.862389  0.306098     NaN
4  0.333914  0.049874  0.788520  0.298697  0.044108     NaN

In [42]:
newdf.drop(0,axis=1)

            A         B         C         D         E
0      0.3453  0.682398  0.660739  0.964293  0.332738
1    0.987456  0.760719  0.042941  0.439698  0.930810
2    0.339867  0.926514  0.560698  0.833263  0.685824
3    0.508694  0.491297  0.931238  0.862389  0.306098
4    0.333914  0.049874  0.788520  0.298697  0.044108
..        ...       ...       ...       ...       ...
329  0.835277  0.514215  0.330844  0.572943  0.014980
330  0.743643  0.046142  0.096495  0.235695  0.793449
331  0.792602  0.639721  0.432425  0.023883  0.797337
332  0.656214  0.487085  0.558181  0.731227  0.674087
333  0.863502  0.669050  0.329836  0.295134  0.081340

[334 rows x 5 columns]

In [43]:
newdf.head()

          A         B         C         D         E       0
0    0.3453  0.682398  0.660739  0.964293  0.332738  0.3456
1  0.987456  0.760719  0.042941  0.439698  0.930810     NaN
2  0.339867  0.926514  0.560698  0.833263  0.685824     NaN
3  0.508694  0.491297  0.931238  0.862389  0.306098     NaN
4  0.333914  0.049874  0.788520  0.298697  0.044108     NaN

In [44]:
newdf.loc[[1,2],['C','D']]

          C         D
1  0.042941  0.439698
2  0.560698  0.833263

In [45]:
newdf.loc[:,['C','D']]

            C         D
0    0.660739  0.964293
1    0.042941  0.439698
2    0.560698  0.833263
3    0.931238  0.862389
4    0.788520  0.298697
..        ...       ...
329  0.330844  0.572943
330  0.096495  0.235695
331  0.432425  0.023883
332  0.558181  0.731227
333  0.329836  0.295134

[334 rows x 2 columns]

In [46]:
newdf.loc[[1,2],:]

          A         B         C         D         E   0
1  0.987456  0.760719  0.042941  0.439698  0.930810 NaN
2  0.339867  0.926514  0.560698  0.833263  0.685824 NaN

In [47]:
newdf.loc[newdf['A']<0.3]

            A         B         C         D         E   0
11   0.143639  0.323048  0.538735  0.040946  0.796826 NaN
13   0.175478  0.958639  0.459357  0.272510  0.902652 NaN
15   0.069269  0.478353  0.628140  0.309715  0.857666 NaN
22   0.255761  0.105983  0.650531  0.219330  0.877588 NaN
25   0.218832  0.985049  0.133005  0.422978  0.557739 NaN
..        ...       ...       ...       ...       ...  ..
293  0.167403  0.418233  0.774207  0.555854  0.900126 NaN
316  0.265107  0.137828  0.616918  0.322131  0.663086 NaN
324   0.11464  0.992715  0.916993  0.566642  0.805476 NaN
325  0.002955  0.888497  0.525628  0.224639  0.912161 NaN
327  0.285912  0.713043  0.891370  0.320539  0.328449 NaN

[82 rows x 6 columns]

In [48]:
newdf.drop([0],axis=1,inplace=True)

In [49]:
newdf

            A         B         C         D         E
0      0.3453  0.682398  0.660739  0.964293  0.332738
1    0.987456  0.760719  0.042941  0.439698  0.930810
2    0.339867  0.926514  0.560698  0.833263  0.685824
3    0.508694  0.491297  0.931238  0.862389  0.306098
4    0.333914  0.049874  0.788520  0.298697  0.044108
..        ...       ...       ...       ...       ...
329  0.835277  0.514215  0.330844  0.572943  0.014980
330  0.743643  0.046142  0.096495  0.235695  0.793449
331  0.792602  0.639721  0.432425  0.023883  0.797337
332  0.656214  0.487085  0.558181  0.731227  0.674087
333  0.863502  0.669050  0.329836  0.295134  0.081340

[334 rows x 5 columns]

In [50]:
newdf.drop([0,3],axis=0,inplace=True)

In [51]:
newdf

            A         B         C         D         E
1    0.987456  0.760719  0.042941  0.439698  0.930810
2    0.339867  0.926514  0.560698  0.833263  0.685824
4    0.333914  0.049874  0.788520  0.298697  0.044108
5    0.471778  0.797376  0.204768  0.975321  0.533654
6    0.875859  0.258019  0.365322  0.946751  0.876808
..        ...       ...       ...       ...       ...
329  0.835277  0.514215  0.330844  0.572943  0.014980
330  0.743643  0.046142  0.096495  0.235695  0.793449
331  0.792602  0.639721  0.432425  0.023883  0.797337
332  0.656214  0.487085  0.558181  0.731227  0.674087
333  0.863502  0.669050  0.329836  0.295134  0.081340

[332 rows x 5 columns]

In [52]:
newdf.head(3)

          A         B         C         D         E
1  0.987456  0.760719  0.042941  0.439698  0.930810
2  0.339867  0.926514  0.560698  0.833263  0.685824
4  0.333914  0.049874  0.788520  0.298697  0.044108

In [53]:
newdf.reset_index()

     index         A         B         C         D         E
0        1  0.987456  0.760719  0.042941  0.439698  0.930810
1        2  0.339867  0.926514  0.560698  0.833263  0.685824
2        4  0.333914  0.049874  0.788520  0.298697  0.044108
3        5  0.471778  0.797376  0.204768  0.975321  0.533654
4        6  0.875859  0.258019  0.365322  0.946751  0.876808
..     ...       ...       ...       ...       ...       ...
327    329  0.835277  0.514215  0.330844  0.572943  0.014980
328    330  0.743643  0.046142  0.096495  0.235695  0.793449
329    331  0.792602  0.639721  0.432425  0.023883  0.797337
330    332  0.656214  0.487085  0.558181  0.731227  0.674087
331    333  0.863502  0.669050  0.329836  0.295134  0.081340

[332 rows x 6 columns]

In [54]:
newdf.head(3)

          A         B         C         D         E
1  0.987456  0.760719  0.042941  0.439698  0.930810
2  0.339867  0.926514  0.560698  0.833263  0.685824
4  0.333914  0.049874  0.788520  0.298697  0.044108

In [55]:
newdf.reset_index(drop=True,inplace=True)

In [56]:
newdf

            A         B         C         D         E
0    0.987456  0.760719  0.042941  0.439698  0.930810
1    0.339867  0.926514  0.560698  0.833263  0.685824
2    0.333914  0.049874  0.788520  0.298697  0.044108
3    0.471778  0.797376  0.204768  0.975321  0.533654
4    0.875859  0.258019  0.365322  0.946751  0.876808
..        ...       ...       ...       ...       ...
327  0.835277  0.514215  0.330844  0.572943  0.014980
328  0.743643  0.046142  0.096495  0.235695  0.793449
329  0.792602  0.639721  0.432425  0.023883  0.797337
330  0.656214  0.487085  0.558181  0.731227  0.674087
331  0.863502  0.669050  0.329836  0.295134  0.081340

[332 rows x 5 columns]

In [57]:
newdf.head(3)

          A         B         C         D         E
0  0.987456  0.760719  0.042941  0.439698  0.930810
1  0.339867  0.926514  0.560698  0.833263  0.685824
2  0.333914  0.049874  0.788520  0.298697  0.044108

In [58]:
newdf['B'].isnull()

0      False
1      False
2      False
3      False
4      False
       ...
327    False
328    False
329    False
330    False
331    False
Name: B, Length: 332, dtype: bool

In [59]:
newdf['B']=None

In [60]:
newdf

            A     B         C         D         E
0    0.987456  None  0.042941  0.439698  0.930810
1    0.339867  None  0.560698  0.833263  0.685824
2    0.333914  None  0.788520  0.298697  0.044108
3    0.471778  None  0.204768  0.975321  0.533654
4    0.875859  None  0.365322  0.946751  0.876808
..        ...   ...       ...       ...       ...
327  0.835277  None  0.330844  0.572943  0.014980
328  0.743643  None  0.096495  0.235695  0.793449
329  0.792602  None  0.432425  0.023883  0.797337
330  0.656214  None  0.558181  0.731227  0.674087
331  0.863502  None  0.329836  0.295134  0.081340

[332 rows x 5 columns]

In [61]:
newdf['B'].isnull()

0      True
1      True
2      True
3      True
4      True
       ...
327    True
328    True
329    True
330    True
331    True
Name: B, Length: 332, dtype: bool

In [62]:
newdf['B']=34

In [63]:
newdf

            A   B         C         D         E
0    0.987456  34  0.042941  0.439698  0.930810
1    0.339867  34  0.560698  0.833263  0.685824
2    0.333914  34  0.788520  0.298697  0.044108
3    0.471778  34  0.204768  0.975321  0.533654
4    0.875859  34  0.365322  0.946751  0.876808
..        ...  ..       ...       ...       ...
327  0.835277  34  0.330844  0.572943  0.014980
328  0.743643  34  0.096495  0.235695  0.793449
329  0.792602  34  0.432425  0.023883  0.797337
330  0.656214  34  0.558181  0.731227  0.674087
331  0.863502  34  0.329836  0.295134  0.081340

[332 rows x 5 columns]

In [64]:
df=pd.DataFrame({'name':["ab","bc","cd"],
                 "toy":[np.nan,np.nan,np.nan],
                 "born":[pd.NaT,pd.Timestamp("160-08-25"),pd.NaT]})

In [65]:
df.head()

  name  toy                 born
0   ab  NaN                  NaT
1   bc  NaN  0160-08-25 00:00:00
2   cd  NaN                  NaT

In [66]:
df.dropna()

Empty DataFrame
Columns: [name, toy, born]
Index: []

In [67]:
df

  name  toy                 born
0   ab  NaN                  NaT
1   bc  NaN  0160-08-25 00:00:00
2   cd  NaN                  NaT

In [68]:
df.dropna(how="all")

  name  toy                 born
0   ab  NaN                  NaT
1   bc  NaN  0160-08-25 00:00:00
2   cd  NaN                  NaT

In [69]:
df

  name  toy                 born
0   ab  NaN                  NaT
1   bc  NaN  0160-08-25 00:00:00
2   cd  NaN                  NaT

In [70]:
df

  name  toy                 born
0   ab  NaN                  NaT
1   bc  NaN  0160-08-25 00:00:00
2   cd  NaN                  NaT

In [71]:
df.dropna(how="all",axis=1)

  name                 born
0   ab                  NaT
1   bc  0160-08-25 00:00:00
2   cd                  NaT

In [72]:
df.drop_duplicates(subset=['name'],keep='last')

  name  toy                 born
0   ab  NaN                  NaT
1   bc  NaN  0160-08-25 00:00:00
2   cd  NaN                  NaT

In [73]:
df.drop_duplicates(subset=['name'],keep=False)

  name  toy                 born
0   ab  NaN                  NaT
1   bc  NaN  0160-08-25 00:00:00
2   cd  NaN                  NaT

In [74]:
df.shape

(3, 3)

In [75]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3 entries, 0 to 2
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   name    3 non-null      object
 1   toy     0 non-null      float64
 2   born    1 non-null      object
dtypes: float64(1), object(2)
memory usage: 200.0+ bytes

In [76]:
df['name'].value_counts(dropna=False)

name
ab    1
bc    1
cd    1
Name: count, dtype: int64

In [77]:
df['name'].value_counts(dropna=True)

name
ab    1
bc    1
cd    1
Name: count, dtype: int64

In [78]:
df.notnull()

   name    toy   born
0  True  False  False
1  True  False   True
2  True  False  False

In [79]:
#create a dataframe which contains only integer with 3 row and 3 column 
#run following dataframe method on them:
#df.describe()
#df.mean()
#df.corr()
#df.count()
#df.max()
#df.min()
#df.median()
#df.std()

In [80]:
df

  name  toy                 born
0   ab  NaN                  NaT
1   bc  NaN  0160-08-25 00:00:00
2   cd  NaN                  NaT